# Generated by Django 4.2.4 on 2023-08-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_setting_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='full_name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
