# Generated by Django 4.2.4 on 2023-08-31 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_setting_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='setting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.setting'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='externallink',
            name='setting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.setting'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='setting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.setting'),
            preserve_default=False,
        ),
    ]
