# Generated by Django 4.2.4 on 2023-09-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_contactform_setting_externallink_setting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='copyright',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='footer_description',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='hero_description',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='project_description',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
