# Generated by Django 4.2.4 on 2023-09-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_project_short_description_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.TextField(default=11),
            preserve_default=False,
        ),
    ]
