# Generated by Django 4.2.4 on 2023-09-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_project_code_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='github_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='instagram_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='linkedin_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='twitter_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='youtube_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
